# Time Series Transformation

Prepare monthly sales and profit data for trend analysis and forecasting.

## Load Validated Dataset
Load the cleaned and validated dataset for time series transformation.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:/Projects/super-store-orders-forecasting/01_data_source/superstore_cleaned.csv")
df["order_date"] = pd.to_datetime(df["order_date"])
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,shipping_cost,order_priority,year,shipping_days,order_month,order_month_name,order_year,order_year_month,profit_margin,discount_flag
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,35.46,Medium,2011,5,1,January,2011,2011-01,0.260147,No Discount
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,9.72,Medium,2011,7,1,January,2011,2011-01,0.300300,Discounted
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,8.17,High,2011,4,1,January,2011,2011-01,0.449091,No Discount
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,4.82,High,2011,4,1,January,2011,2011-01,-0.579000,Discounted
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,4.70,Medium,2011,7,1,January,2011,2011-01,0.331316,Discounted

## Review Date Coverage
Confirm the dataset spans an appropriate time range for monthly trend analysis.

In [3]:
df["order_date"].min(), df["order_date"].max()

(Timestamp('2011-01-01 00:00:00'), Timestamp('2014-12-31 00:00:00'))

## Aggregate Monthly Sales and Profit
Group transaction-level data by month to create a time series dataset for analysis.

In [5]:
monthly_sales = (
    df.groupby(pd.Grouper(key="order_date", freq="ME"))
    .agg(
        total_sales=("sales", "sum"),
        total_profit=("profit", "sum")
    )
    .reset_index()
)

monthly_sales.head()

  order_date  total_sales  total_profit
0 2011-01-31      64363.0    3857.14052
1 2011-02-28      60848.0    5126.20778
2 2011-03-31      78983.0    7394.58030
3 2011-04-30      80698.0    6719.46738
4 2011-05-31      91536.0    5133.88400

## Sort Monthly Data
Ensure the monthly dataset is ordered correctly for trend calculations.

In [7]:
monthly_sales = monthly_sales.sort_values("order_date").reset_index(drop=True)
monthly_sales.head()

  order_date  total_sales  total_profit    month
0 2011-01-31      64363.0    3857.14052  2011-01
1 2011-02-28      60848.0    5126.20778  2011-02
2 2011-03-31      78983.0    7394.58030  2011-03
3 2011-04-30      80698.0    6719.46738  2011-04
4 2011-05-31      91536.0    5133.88400  2011-05

## Create Rolling Averages
Calculate rolling averages to smooth short-term fluctuations and highlight longer-term trends.

In [8]:
monthly_sales["rolling_sales_3mo"] = monthly_sales["total_sales"].rolling(window=3).mean()
monthly_sales["rolling_profit_3mo"] = monthly_sales["total_profit"].rolling(window=3).mean()

monthly_sales.head(10)

,order_date,total_sales,total_profit,month,rolling_sales_3mo,rolling_profit_3mo
0,2011-01-31,64363.0,3857.14052,2011-01,NaN,NaN
1,2011-02-28,60848.0,5126.20778,2011-02,NaN,NaN
2,2011-03-31,78983.0,7394.58030,2011-03,68064.666667,5459.309533
3,2011-04-30,80698.0,6719.46738,2011-04,73509.666667,6413.418487
4,2011-05-31,91536.0,5133.88400,2011-05,83739.000000,6415.977227
5,2011-06-30,142526.0,9528.76554,2011-06,104920.000000,7127.372307
6,2011-07-31,75412.0,4070.57182,2011-07,103158.000000,6244.407120
7,2011-08-31,132065.0,13841.75724,2011-08,116667.666667,9147.031533
8,2011-09-30,153992.0,14391.33644,2011-09,120489.666667,10767.888500
9,2011-10-31,122853.0,11661.53748,2011-10,136303.333333,13298.210387

## Review Time Series Output
Inspect the final monthly dataset before using it for visualization and forecasting.

In [9]:
monthly_sales.info()
monthly_sales.describe()
monthly_sales.head(12)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_date          48 non-null     datetime64[ns]
 1   total_sales         48 non-null     float64
 2   total_profit        48 non-null     float64
 3   month               48 non-null     object
 4   rolling_sales_3mo   46 non-null     float64
 5   rolling_profit_3mo  46 non-null     float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.4+ KB

,order_date,total_sales,total_profit,month,rolling_sales_3mo,rolling_profit_3mo
0,2011-01-31,64363.0,3857.14052,2011-01,NaN,NaN
1,2011-02-28,60848.0,5126.20778,2011-02,NaN,NaN
2,2011-03-31,78983.0,7394.58030,2011-03,68064.666667,5459.309533
3,2011-04-30,80698.0,6719.46738,2011-04,73509.666667,6413.418487
4,2011-05-31,91536.0,5133.88400,2011-05,83739.000000,6415.977227
5,2011-06-30,142526.0,9528.76554,2011-06,104920.000000,7127.372307
6,2011-07-31,75412.0,4070.57182,2011-07,103158.000000,6244.407120
7,2011-08-31,132065.0,13841.75724,2011-08,116667.666667,9147.031533
8,2011-09-30,153992.0,14391.33644,2011-09,120489.666667,10767.888500
9,2011-10-31,122853.0,11661.53748,2011-10,136303.333333,13298.210387
10,2011-11-30,175221.0,15734.90322,2011-11,150688.666667,13929.259047
11,2011-12-31,199654.0,14907.18194,2011-12,165909.333333,14101.207547

## Export Monthly Dataset
Save the transformed monthly dataset for forecasting and dashboard development.

In [10]:
monthly_sales.to_csv("D:/Projects/super-store-orders-forecasting/03_analysis_output/monthly_sales_timeseries.csv", index=False)

In [11]:
print("Clean dataset successfully exported.")

Clean dataset successfully exported.